apiVersion: v1
kind: Service
metadata:
    name: example-simple-nginx
spec:
    ports:
        -   port: 80
            targetPort: 80
            protocol: TCP
            name: http
    selector:
        app: example-simple-nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: example-simple-nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: example-simple-nginx
    template:
        metadata:
            labels:
                app: example-simple-nginx
        spec:
            containers:
                -   name: example-simple-nginx
                    image: docker.pkg.github.com/extraton/example-simple/example-simple-nginx:0.1
                    ports: [{containerPort: 80}]
            imagePullSecrets:
                -   name: github-registry
